export const UPDATE_VIEW = 'UPDATE_VIEW';
export const UPDATE_MAP = 'UPDATE_MAP';
export const UPDATE_SELECTED = 'UPDATE_SELECTED';
export const UPDATE_DRAWER = 'UPDATE_DRAWER';
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';
export const UPDATE_LAYER = 'UPDATE_LAYER';
